#!/usr/bin/env python3
"""Smoke-test exported ONNX with onnxruntime and document tensor I/O."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import onnxruntime as ort

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MODEL = ROOT / "public" / "models" / "best.onnx"
MODEL_IO_DOC = ROOT / "docs" / "MODEL_IO.md"


def document_io(session: ort.InferenceSession, model_path: Path) -> None:
    lines = [
        "# Model I/O (auto-generated by verify_onnx.py)",
        "",
        f"Model path: `{model_path.relative_to(ROOT)}`",
        "",
        "## Inputs",
        "",
    ]
    for inp in session.get_inputs():
        lines.append(f"- **{inp.name}**: shape `{inp.shape}`, type `{inp.type}`")
    lines.extend(["", "## Outputs", ""])
    for out in session.get_outputs():
        lines.append(f"- **{out.name}**: shape `{out.shape}`, type `{out.type}`")
    lines.extend(
        [
            "",
            "## Frontend usage",
            "",
            "- Input name for `session.run`: use the input name listed above (typically `images`).",
            "- Preprocess: letterbox to 640x640, RGB, NCHW, normalize to [0, 1].",
            "- Postprocess: YOLOv8-pose decode + NMS (see `src/decoder.js`).",
            "",
        ]
    )
    MODEL_IO_DOC.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {MODEL_IO_DOC}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    args = parser.parse_args()
    model_path = args.model.resolve()

    if not model_path.is_file():
        print(f"ERROR: ONNX not found: {model_path}")
        print("Train and export first: python python/train.py --data data.yaml")
        return 1

    session = ort.InferenceSession(str(model_path), providers=["CPUExecutionProvider"])
    inp = session.get_inputs()[0]
    h, w = 640, 640
    if len(inp.shape) == 4:
        _, _, h, w = [d if isinstance(d, int) else 640 for d in inp.shape]

    dummy = np.random.rand(1, 3, h, w).astype(np.float32)
    outputs = session.run(None, {inp.name: dummy})
    print(f"Input: {inp.name} shape (1, 3, {h}, {w})")
    for i, out in enumerate(session.get_outputs()):
        arr = outputs[i]
        print(f"Output[{i}] {out.name}: shape {arr.shape} dtype {arr.dtype}")

    document_io(session, model_path)
    print("ONNX smoke test OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
